language: java
sudo: false
jdk:
  - oraclejdk8
install: true
script:
# We fetch all dependencies but we don't print the output so it's more digest
  - mvn clean dependency:resolve dependency:resolve-plugins > /dev/null
# Let's skip for now branch 1.x
#  - mvn clean verify -Pes-1x
#  - mvn clean verify -Pes-2x-travis
  - mvn clean verify -Dtests.output=always -DskipUnitTests=true -DskipXPack=true
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings deploy-settings.xml"
#after_success:
#  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings deploy-settings.xml"
after_failure:
  - echo "As we got a failure, let's see what we have in elasticsearch cluster logs"
  - cat target/integration-tests/run/elasticsearch-*/logs/elasticsearch_integration.log

